Fix black --exclude replacing defaults, use --extend-exclude

diff --git a/.github/workflows/submission.yml b/.github/workflows/submission.yml
--- a/.github/workflows/submission.yml
+++ b/.github/workflows/submission.yml
@@ -109,7 +109,7 @@ jobs:
         id: black
         continue-on-error: true
         run: |
-          black --check . --exclude tests/ || echo "black_failed=true" >> $GITHUB_OUTPUT
+          black --check . --extend-exclude tests/ || echo "black_failed=true" >> $GITHUB_OUTPUT
 
       - name: Lint summary
         run: |
